name: 'fetch rls'
description: 'Fetch latest release ticket metadata'
inputs:
  parentTicket:
    description: 'Release parent ticket'
    required: true
    default: 'CXT-1876'
  jira_secret:
    description: 'Jira secret'
    required: true
    default: 'XXXXX'
outputs:
  whatever:
    description: 'Whatever'
runs:
  using: 'node20'
  main: 'index.js'
