name: 'fetch rls'
description: 'Fetch latest release ticket metadata'
inputs:
  parent_ticket:
    description: 'Release parent ticket. Usually indicates that the current ticket is a \"release\" ticket'
    required: true
    default: 'CXT-1876'
  jira_secret:
    description: 'Jira secret'
    required: true
  head_commit:
    description: 'Current HEAD commit'
    required: true
  repository_name:
    description: 'Repository name'
    required: true
  github_secret:
    description: 'Github secret'
    required: true
  branch_name:
    description: 'Released branch name'
    required: true
outputs:
  rls_ticket_url:
    description: 'Generated Jira release ticket URL'
runs:
  using: 'node20'
  main: 'index.js'
